root_fold<-'inst/app/www/'
b64 <- base64enc::dataURI(file=paste0(root_fold,"introduction.png"), mime="www/png")
tab1 <- fluidRow(
  shinydashboard::box(width=6, height = 100, checkboxGroupInput("filter1", "expression type of DDA:",
                         c("top0" = "top0",
                           "top3" = "top3",
                           "count" = "count",
                           "MaxLFQ" = 'LFQ',
                           "directLFQ" = "dlfq"), inline = TRUE)),
  shinydashboard::box(width=6, height = 100,checkboxGroupInput("filter2", "normalization:",
                         c("No_normalization" = "None",
                           "center.mean" = "center.mean",
                           "center.median" = "center.median",
                           "max" = "max",
                           "sum" = "sum",
                           "vsn" = "vsn",
                           "quantiles" = "quantiles",
                           "quantiles.robust" = "quantiles.robust",
                           "div.mean" = "div.mean",
                           "div.median" = "div.median",
                           'lossf' = 'lossf',
                           'TIC' = 'TIC',
                           "Rlr" = "Rlr",
                           'MBQN' = 'MBQN'
                         ), inline = TRUE)),
  shinydashboard::box(width=6, height = 100,checkboxGroupInput("filter3", "MVI:",
                         c("MinProb" = "MinProb",
                           "QRILC" = "QRILC",
                           "MinDet" = "MinDet",
                           "missForest" = "missForest",
                           "nbavg" = "nbavg",
                           "zero" = "zero",
                           "bpca" = "bpca",
                           "MLE" = "MLE",
                           "knn" = "knn",
                           "No_MVI" = "None",
                           "min" = "min",
                           "mice" = "mice",
                           "Impseq" = "Impseq",
                           "Impseqrob" = "Impseqrob",
                           "GMS" = "GMS",
                           'SeqKNN' = 'SeqKNN'), inline = TRUE)),
  shinydashboard::box(width=6, height = 100,checkboxGroupInput("filter4", "DEA tool:",
                         c("ANOVA" = "ANOVA",
                           "DEP" = "DEP",
                           "DEqMS" = "DEqMS",
                           'limma' = "limma",
                           "proDA" = "proDA",
                           "ROTS" = "ROTS",
                           "SAM" = "SAM",
                           "ttest" = "ttest",
                           "beta_binomial" = "beta_binomial",
                           "edgeR" = "edgeR",
                           "plgem" = "plgem",
                           'MSstats' = 'MSstats'
                         ), inline = TRUE)),
  shinydashboard::box(width = 6, height = 600,
      "workflow benchmarking",
      br(),
      column(width = 12,DT::dataTableOutput("tabFrag"), style = "height:500px; overflow-x: scroll;")
  ),
  shinydashboard::box(width = 6, height = 600,
      "performance distributions",
      br(),
      plotOutput("boxplot1", height = 500, width = 500)
  )
)

tab2 <- fluidRow(
  shinydashboard::box(width=6, height = 100,checkboxGroupInput("filter5", "expression type of DDA:",
                                                               c("top0" = "top0",
                                                                 "top3" = "top3",
                                                                 "count" = "count",
                                                                 "MaxLFQ" = 'LFQ',
                                                                 "directLFQ" = "dlfq"), inline = TRUE)),
  shinydashboard::box(width=6, height = 100,checkboxGroupInput("filter6", "normalization:",
                                                               c("No_normalization" = "None",
                                                                 "center.mean" = "center.mean",
                                                                 "center.median" = "center.median",
                                                                 "max" = "max",
                                                                 "sum" = "sum",
                                                                 "vsn" = "vsn",
                                                                 "quantiles" = "quantiles",
                                                                 "quantiles.robust" = "quantiles.robust",
                                                                 "div.mean" = "div.mean",
                                                                 "div.median" = "div.median",
                                                                 'lossf' = 'lossf',
                                                                 'TIC' = 'TIC',
                                                                 "Rlr" = "Rlr",
                                                                 'MBQN' = 'MBQN'
                                                               ), inline = TRUE)),
  shinydashboard::box(width=6, height = 100,checkboxGroupInput("filter7", "MVI:",
                                                               c("MinProb" = "MinProb",
                                                                 "QRILC" = "QRILC",
                                                                 "MinDet" = "MinDet",
                                                                 "missForest" = "missForest",
                                                                 "nbavg" = "nbavg",
                                                                 "zero" = "zero",
                                                                 "bpca" = "bpca",
                                                                 "MLE" = "MLE",
                                                                 "knn" = "knn",
                                                                 "No_MVI" = "None",
                                                                 "min" = "min",
                                                                 "mice" = "mice",
                                                                 "Impseq" = "Impseq",
                                                                 "Impseqrob" = "Impseqrob",
                                                                 "GMS" = "GMS",
                                                                 'SeqKNN' = 'SeqKNN'), inline = TRUE)),
  shinydashboard::box(width=6, height = 100,checkboxGroupInput("filter8", "DEA tool:",
                                                               c("ANOVA" = "ANOVA",
                                                                 "DEP" = "DEP",
                                                                 "DEqMS" = "DEqMS",
                                                                 'limma' = "limma",
                                                                 "proDA" = "proDA",
                                                                 "ROTS" = "ROTS",
                                                                 "SAM" = "SAM",
                                                                 "ttest" = "ttest",
                                                                 "beta_binomial" = "beta_binomial",
                                                                 "edgeR" = "edgeR",
                                                                 "plgem" = "plgem",
                                                                 'MSstats' = 'MSstats'
                                                               ), inline = TRUE)),
  shinydashboard::box(width = 6, height = 600,
      "workflow benchmarking",
      br(),
      column(width = 12,DT::dataTableOutput("tabMq"), style = "height:500px; overflow-x: scroll;")
  ),
  shinydashboard::box(width = 6, height = 600,
      "performance distributions",
      br(),
      plotOutput("boxplot2", height = 500, width = 500)
  )
)

tab3 <- fluidRow(
  shinydashboard::box(width=6, height = 100,checkboxGroupInput("filter9", "expression type of DIA:",
                                                               c("top1" = "top1",
                                                                 "top3" = "top3",
                                                                 #"count" = "sc",
                                                                 "MaxLFQ" = 'LFQ',
                                                                 "directLFQ" = "dlfq"), inline = TRUE)),
  shinydashboard::box(width=6, height = 100,checkboxGroupInput("filter10", "normalization:",
                                                               c("No_normalization" = "None",
                                                                 "center.mean" = "center.mean",
                                                                 "center.median" = "center.median",
                                                                 "max" = "max",
                                                                 "sum" = "sum",
                                                                 "vsn" = "vsn",
                                                                 "quantiles" = "quantiles",
                                                                 "quantiles.robust" = "quantiles.robust",
                                                                 "div.mean" = "div.mean",
                                                                 "div.median" = "div.median",
                                                                 'lossf' = 'lossf',
                                                                 'TIC' = 'TIC',
                                                                 "Rlr" = "Rlr",
                                                                 'MBQN' = 'MBQN'
                                                               ), inline = TRUE)),
  shinydashboard::box(width=6, height = 100,checkboxGroupInput("filter11", "MVI:",
                                                               c("MinProb" = "MinProb",
                                                                 "QRILC" = "QRILC",
                                                                 "MinDet" = "MinDet",
                                                                 "missForest" = "missForest",
                                                                 "nbavg" = "nbavg",
                                                                 "zero" = "zero",
                                                                 "bpca" = "bpca",
                                                                 "MLE" = "MLE",
                                                                 "knn" = "knn",
                                                                 "No_MVI" = "None",
                                                                 "min" = "min",
                                                                 "mice" = "mice",
                                                                 "Impseq" = "Impseq",
                                                                 "Impseqrob" = "Impseqrob",
                                                                 "GMS" = "GMS",
                                                                 'SeqKNN' = 'SeqKNN'), inline = TRUE)),
  shinydashboard::box(width=6, height = 100,checkboxGroupInput("filter12", "DEA tool:",
                                                               c("ANOVA" = "ANOVA",
                                                                 "DEP" = "DEP",
                                                                 #"DEqMS" = "DEqMS",
                                                                 'limma' = "limma",
                                                                 "proDA" = "proDA",
                                                                 "ROTS" = "ROTS",
                                                                 "SAM" = "SAM",
                                                                 "ttest" = "ttest",
                                                                 #"beta_binomial" = "beta_binomial",
                                                                 #"edgeR" = "edgeR",
                                                                 #"plgem" = "plgem",
                                                                 'MSstats' = 'MSstats'
                                                               ), inline = TRUE)),
  shinydashboard::box(width = 6, height = 600,
      "workflow benchmarking",
      br(),
      column(width = 12,DT::dataTableOutput("tabDia"), style = "height:500px; overflow-x: scroll;")
  ),
  shinydashboard::box(width = 6, height = 600,
      "performance distributions",
      br(),
      plotOutput("boxplot3", height = 500, width = 500)
  )
)

tab4 <- fluidRow(
  shinydashboard::box(width=6, height = 100,checkboxGroupInput("filter13", "expression type of DIA:",
                                                               c("top1" = "top1",
                                                                 "top3" = "top3",
                                                                 #"count" = "sc",
                                                                 "MaxLFQ" = 'LFQ',
                                                                 "directLFQ" = "dlfq"), inline = TRUE)),
  shinydashboard::box(width=6, height = 100,checkboxGroupInput("filter14", "normalization:",
                                                               c("No_normalization" = "None",
                                                                 "center.mean" = "center.mean",
                                                                 "center.median" = "center.median",
                                                                 "max" = "max",
                                                                 "sum" = "sum",
                                                                 "vsn" = "vsn",
                                                                 "quantiles" = "quantiles",
                                                                 "quantiles.robust" = "quantiles.robust",
                                                                 "div.mean" = "div.mean",
                                                                 "div.median" = "div.median",
                                                                 'lossf' = 'lossf',
                                                                 'TIC' = 'TIC',
                                                                 "Rlr" = "Rlr",
                                                                 'MBQN' = 'MBQN'
                                                               ), inline = TRUE)),
  shinydashboard::box(width=6, height = 100,checkboxGroupInput("filter15", "MVI:",
                                                               c("MinProb" = "MinProb",
                                                                 "QRILC" = "QRILC",
                                                                 "MinDet" = "MinDet",
                                                                 "missForest" = "missForest",
                                                                 "nbavg" = "nbavg",
                                                                 "zero" = "zero",
                                                                 "bpca" = "bpca",
                                                                 "MLE" = "MLE",
                                                                 "knn" = "knn",
                                                                 "No_MVI" = "None",
                                                                 "min" = "min",
                                                                 "mice" = "mice",
                                                                 "Impseq" = "Impseq",
                                                                 "Impseqrob" = "Impseqrob",
                                                                 "GMS" = "GMS",
                                                                 'SeqKNN' = 'SeqKNN'), inline = TRUE)),
  shinydashboard::box(width=6, height = 100,checkboxGroupInput("filter16", "DEA tool:",
                                                               c("ANOVA" = "ANOVA",
                                                                 "DEP" = "DEP",
                                                                 #"DEqMS" = "DEqMS",
                                                                 'limma' = "limma",
                                                                 "proDA" = "proDA",
                                                                 "ROTS" = "ROTS",
                                                                 "SAM" = "SAM",
                                                                 "ttest" = "ttest",
                                                                 #"beta_binomial" = "beta_binomial",
                                                                 #"edgeR" = "edgeR",
                                                                 #"plgem" = "plgem",
                                                                 'MSstats' = 'MSstats'
                                                               ), inline = TRUE)),
  shinydashboard::box(width = 6, height = 600,
                      "workflow benchmarking",
                      br(),
                      column(width = 12,DT::dataTableOutput("tabDia1"), style = "height:500px; overflow-x: scroll;")
  ),
  shinydashboard::box(width = 6, height = 600,
                      "performance distributions",
                      br(),
                      plotOutput("boxplot4", height = 500, width = 500)
  )
)

tab5 <- fluidRow(
  shinydashboard::box(width=6, height = 100,checkboxGroupInput("filter17", "expression type of TMT:",
                                                               c("abd" = "abd",
                                                                 "ratio" = "ratio",
                                                                 "phi" = "phi"
                                                                 #"norm_raw" = "norm_raw",
                                                                 ), inline = TRUE)),
  shinydashboard::box(width=6, height = 100,checkboxGroupInput("filter18", "normalization:",
                                                               c("No_normalization" = "None",
                                                                 "center.mean" = "center.mean",
                                                                 "center.median" = "center.median",
                                                                 "max" = "max",
                                                                 "sum" = "sum",
                                                                 "vsn" = "vsn",
                                                                 "quantiles" = "quantiles",
                                                                 "quantiles.robust" = "quantiles.robust",
                                                                 "div.mean" = "div.mean",
                                                                 "div.median" = "div.median",
                                                                 'lossf' = 'lossf',
                                                                 'TIC' = 'TIC',
                                                                 "Rlr" = "Rlr",
                                                                 'MBQN' = 'MBQN'
                                                               ), inline = TRUE)),
  shinydashboard::box(width=6, height = 100,checkboxGroupInput("filter19", "MVI:",
                                                               c("MinProb" = "MinProb",
                                                                 "QRILC" = "QRILC",
                                                                 "MinDet" = "MinDet",
                                                                 "missForest" = "missForest",
                                                                 "nbavg" = "nbavg",
                                                                 "zero" = "zero",
                                                                 "bpca" = "bpca",
                                                                 "MLE" = "MLE",
                                                                 "knn" = "knn",
                                                                 "No_MVI" = "None",
                                                                 "min" = "min",
                                                                 "mice" = "mice",
                                                                 "Impseq" = "Impseq",
                                                                 "Impseqrob" = "Impseqrob",
                                                                 "GMS" = "GMS",
                                                                 'SeqKNN' = 'SeqKNN'), inline = TRUE)),
  shinydashboard::box(width=6, height = 100,checkboxGroupInput("filter20", "DEA tool:",
                                                               c("ANOVA" = "ANOVA",
                                                                 "DEP" = "DEP",
                                                                 #"DEqMS" = "DEqMS",
                                                                 'limma' = "limma",
                                                                 "proDA" = "proDA",
                                                                 "ROTS" = "ROTS",
                                                                 "SAM" = "SAM",
                                                                 "ttest" = "ttest",
                                                                 #"beta_binomial" = "beta_binomial",
                                                                 #"edgeR" = "edgeR",
                                                                 #"plgem" = "plgem",
                                                                 'MSstats' = 'MSstats'
                                                               ), inline = TRUE)),
  shinydashboard::box(width = 6, height = 600,
                      "workflow benchmarking",
                      br(),
                      column(width = 12,DT::dataTableOutput("tabTMT1"), style = "height:500px; overflow-x: scroll;")
  ),
  shinydashboard::box(width = 6, height = 600,
                      "performance distributions",
                      br(),
                      plotOutput("boxplot5", height = 500, width = 500)
  )
)


tab6 <- fluidRow(
    shinydashboard::box(width=6, height = 100,checkboxGroupInput("filter21", "expression type of TMT:",
                                                               c(
                                                                 "intensity" = "intensity"), inline = TRUE)),
  shinydashboard::box(width=6, height = 100,checkboxGroupInput("filter22", "normalization:",
                                                               c("No_normalization" = "None",
                                                                 "center.mean" = "center.mean",
                                                                 "center.median" = "center.median",
                                                                 "max" = "max",
                                                                 "sum" = "sum",
                                                                 "vsn" = "vsn",
                                                                 "quantiles" = "quantiles",
                                                                 "quantiles.robust" = "quantiles.robust",
                                                                 "div.mean" = "div.mean",
                                                                 "div.median" = "div.median",
                                                                 'lossf' = 'lossf',
                                                                 'TIC' = 'TIC',
                                                                 "Rlr" = "Rlr",
                                                                 'MBQN' = 'MBQN'
                                                               ), inline = TRUE)),
  shinydashboard::box(width=6, height = 100,checkboxGroupInput("filter23", "MVI:",
                                                               c("MinProb" = "MinProb",
                                                                 "QRILC" = "QRILC",
                                                                 "MinDet" = "MinDet",
                                                                 "missForest" = "missForest",
                                                                 "nbavg" = "nbavg",
                                                                 "zero" = "zero",
                                                                 "bpca" = "bpca",
                                                                 "MLE" = "MLE",
                                                                 "knn" = "knn",
                                                                 "No_MVI" = "None",
                                                                 "min" = "min",
                                                                 "mice" = "mice",
                                                                 "Impseq" = "Impseq",
                                                                 "Impseqrob" = "Impseqrob",
                                                                 "GMS" = "GMS",
                                                                 'SeqKNN' = 'SeqKNN'), inline = TRUE)),
  shinydashboard::box(width=6, height = 100,checkboxGroupInput("filter24", "DEA tool:",
                                                               c("ANOVA" = "ANOVA",
                                                                 "DEP" = "DEP",
                                                                 #"DEqMS" = "DEqMS",
                                                                 'limma' = "limma",
                                                                 "proDA" = "proDA",
                                                                 "ROTS" = "ROTS",
                                                                 "SAM" = "SAM",
                                                                 "ttest" = "ttest",
                                                                 #"beta_binomial" = "beta_binomial",
                                                                 #"edgeR" = "edgeR",
                                                                 #"plgem" = "plgem",
                                                                 'MSstats' = 'MSstats'
                                                               ), inline = TRUE)),
  shinydashboard::box(width = 6, height = 600,
                      "workflow benchmarking",
                      br(),
                      column(width = 12,DT::dataTableOutput("tabTMT2"), style = "height:500px; overflow-x: scroll;")
  ),
  shinydashboard::box(width = 6, height = 600,
                      "performance distributions",
                      br(),
                      plotOutput("boxplot6", height = 500, width = 500)
  )
)

tabIntro<-fluidRow(
  shinydashboard::box(
    title = "Abstract",
    background = "green",
    width = 12,
    p("The identification of phenotype-specific or differentially expressed proteins from proteomic data typically involves a workflow encompassing five key steps: raw data quantification, expression matrix construction, matrix normalization, missing data imputation, and differential expression analysis. The abundance of options at each step poses a challenge, as suboptimal combinations may lead to less effective workflows. To predict optimal workflows, we conducted an extensive study involving 34,576 experiments. Our analysis compared exhaustive combinations of option across 24 gold standard spike-in datasets and four quantification platforms: FragPipe, MaxQuant, DIA-NN, and Spectronaut. Employing frequent pattern mining techniques on our experimental data, we uncovered high-performing rules for optimal workflow selection. Key guidelines include employing directLFQ for quantification, avoiding normalization, and utilizing SeqKNN, Impseq, or MinProb for missing value imputation. Additionally, ROTS or limma emerged as preferred choices for differential expression analysis. Optimal workflows proved predictable, allowing accurate categorization with average F1 scores and Matthew's correlation coefficients surpassing 0.84 in 10-fold cross-validations. Integrating top-ranked workflows through ensemble inference not only enhanced the accuracy of differential expression analysis, achieving gains in pAUC and up to 11% in G-mean, but also empowered the workflow to aggregate information across various quantification approaches, such as topN, directLFQ, MaxLFQ intensities, and spectral counts. This comprehensive perspective on the data provides a nuanced understanding of proteome dynamics, allowing us to maximize acquired spectral data. Our study underscores the paramount importance of selecting optimal workflow combinations. It also demonstrates the profound benefits of ensemble inference, not only in improving accuracy but also in enriching the comprehensiveness of proteomic data analysis. Our proposed approach can provide guidance towards refining proteomic methodologies, which in turn, improves its capability for successful biomedical and medical applications.
"))
)

tabWf_intro<-fluidRow(
  shinydashboard::box(
    title = "Workflow of a DEA process for label-free proteomics data and available tools for each step in the workflow",
    background = "navy",
    width = 12,
    img(src=b64, height = "500px", width = "1000px", align = "center")
    # img(src = "img/introduction.png",
    #     height = "500px", width = "1100px", align = "center")
    #HTML('<div id="stats_header"> <img src="img/introduction.png" height = "500px", width = "1100px", align = "center"/> </div>')
    )

)

tabLOPOCV<-fluidRow(
  shinydashboard::box(
    title = "Good Generalizability confirmed by Leave-One-Dataset-Out Cross-Validation",
    background = "purple",
    width = 12,
    textOutput("LOPOCV performances"),
    br(),
    column(12,plotOutput("fgcv"))#,
    #column(4,plotOutput("mqcv")),
    #column(4,plotOutput("diacv"))
    )
)

tabcls<-fluidRow(
  shinydashboard::box(
    title = "Workflow performance levels are predictable",
    background = "light-blue",
    width = 12,
    textOutput("10-fold cross-validation tests results of CatBoost classifiers"),
    br(),
    column(6,plotOutput("cvCls")),
    column(6,plotOutput("feaImp"))
  )
)

tabAC<-fluidRow(
  shinydashboard::box(
    title = "Acknowledgement and Citation",
    background = "orange",
    width = 12,
    h3("Acknowledgement"),
    p("This research/project is supported by the National Research Foundation, Singapore under its Industry Alignment Fund – Prepositioning (IAF-PP) Funding Initiative. Any opinions, findings and conclusions or recommendations expressed in this material are those of the author(s) and do not reflect the views of National Research Foundation, Singapore."),
    p("WWBG also acknowledges support from an MOE Tier 1 award (RS08/21)."),
    br(),
    h3('Publication'),
    p("Please cite the following paper:"),
    p("Hui Peng, He Wang, Weijia Kong, Jinyan Li*, Wilson Wen Bin Goh*. (2023). Optimizing Proteomics Data Differential Expression Analysis via Unveiling High-Performing Rules and Ensemble Inference")
  )
)
